apiVersion: v1
kind: Service
metadata:
  name: openshift
  namespace: openshift-origin
spec:
  ports:
    - name: openshift
      nodePort: 30443
      port: 8443
      targetPort: 8443
  selector:
    name: openshift
  type: NodePort
